### ISSUE TITLE
Removes existing links

### ISSUE THREAD

**Issue by peterberbec** [giveforward/yourls-simplecharset#4]
I like the idea of a simple charset, I planned on:

REMOVE: I & l & 1, O & 0, S & 5, Z & 2

## Error:

My problem is once the plugin is activated, any links created previously get these characters removed from the admin interface.

# Example:

![Good image](http://berb.ec/uploads/good.png)

becomes:

![Bad image](http://berb.ec/uploads/bad.png)

The link http://berb.ec/1lue- works if the plugin is active or not.

## Expected result:

Once activated, the plugin only restricts new links to using the custom charset, not change the admin interface display of current links. It also should allow you to manually create a link with the banned characters, only restricting randomly created ones.

Thanks!

**Comment by cgmckeever** [comment]
I had this same desire/want when developing this.  I think its possible, buts the code hooks are a bit deeper than this plugin originally went.  I may have some time to look into this and/or if you have some time to dig in and submit a PR - that be awesome.

**Comment by peterberbec** [comment]
Yeah, I think where you put the plug in is high up in the function
hierarchy. If one could find where the random generation for new links is
generated, and hook into that, and only that function, it may be possible.
I think I'll try emailing one of the main YOURLS people.

If I get it first, do you just want me to email you some code?

Peter Berbec
(845) 380-5430
On May 24, 2016 8:39 AM, "cgmckeever" <notifications@github.com> wrote:

I had this same desire/want when developing this. I think its possible,
buts the code hooks are a bit deeper than this plugin originally went. I
may have some time to look into this and/or if you have some time to dig in
and submit a PR - that be awesome.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/giveforward/yourls-simplecharset/issues/4#issuecomment-221255145>

**Comment by zpfled** [comment]
+1 :hamster:

- Zach

**Comment by peterberbec** [comment]
Coded it - http://berb.ec/qjtp3 @zpfled
